# -*- coding: utf-8 -*-
"""assignment4 theoretrical.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17jl0EzOf3FiuA649NYvVlQCYy9bC-Yiz
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats
prob_per_true= 3/4
prob_per_false= 1/4
x=['Truth','False']
h=[prob_per_true,prob_per_false]
plt.bar(x,h)
plt.xlabel("X")
plt.ylabel("Probability")
plt.title("(Theoretrical)probability of truth")
plt.show()

prob_dice5=1/6
prob_dice_not_5=5/6
#P(A)=P(A/B)P(B)+P(A/C)P(C)
#Here event A:person telling outcome is 5
# event B:person telling truth
# event c:person telling false
#(outcome is 5)P(B/A)=(P(A/B)*P(B))/P(A)
P_A = 8/24
P_A_by_B= 1/6
P_B = 3/4
dice = P_A_by_B*P_B
prob_dice = dice/P_A
print(f'(Theoretrical)probability of outcome=5 is',prob_dice)
prob_dice_other=1-prob_dice
x=['outcome is not 5','outcome is 5']
h=[prob_dice_other,prob_dice]
plt.bar(x,h)
plt.xlabel("X")
plt.ylabel("Probability")
plt.title("(Theoretrical)probability of outcomes")
plt.show()